// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyDeqpwGrEyfYGpm83g74tjFC5-5EbQUg',
    appId: '1:450181690392:web:17f20acf90110682543f6d',
    messagingSenderId: '450181690392',
    projectId: 'mywallet-dfd2b',
    authDomain: 'mywallet-dfd2b.firebaseapp.com',
    storageBucket: 'mywallet-dfd2b.firebasestorage.app',
    measurementId: 'G-YXVMVZZ2LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj8bUmXGedxDegMmL0TOEnRwnib0Ptl-w',
    appId: '1:450181690392:android:5104e7844124cd72543f6d',
    messagingSenderId: '450181690392',
    projectId: 'mywallet-dfd2b',
    storageBucket: 'mywallet-dfd2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeX5L895W45QUjnz_FW2cKPr2BDoB_L18',
    appId: '1:450181690392:ios:5ca0b310b1aca1e5543f6d',
    messagingSenderId: '450181690392',
    projectId: 'mywallet-dfd2b',
    storageBucket: 'mywallet-dfd2b.firebasestorage.app',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeX5L895W45QUjnz_FW2cKPr2BDoB_L18',
    appId: '1:450181690392:ios:5ca0b310b1aca1e5543f6d',
    messagingSenderId: '450181690392',
    projectId: 'mywallet-dfd2b',
    storageBucket: 'mywallet-dfd2b.firebasestorage.app',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyDeqpwGrEyfYGpm83g74tjFC5-5EbQUg',
    appId: '1:450181690392:web:681fce0114043d0f543f6d',
    messagingSenderId: '450181690392',
    projectId: 'mywallet-dfd2b',
    authDomain: 'mywallet-dfd2b.firebaseapp.com',
    storageBucket: 'mywallet-dfd2b.firebasestorage.app',
    measurementId: 'G-PFKKGR43J7',
  );
}
